(function(root){
'use strict';
const P=typeof module!=='undefined'&&module.exports?require('./publications.js'):root.Publications;
const titles=['EdD Program Update','The Weeks Ahead','EdD Community','Dissertation Journey','Residency','Student Spotlight','Alumni Connection','Research & Public Scholarship','Opportunities','Resources & Support','Community Co-working & Café','Stay Connected / Need Help'];
const ids=['update','weeks','community','dissertation','residency','students','alumni','scholarship','opportunities','resources','cafe','connect'];
const types=['leadership','event','announcement','spotlight','resource','opportunity','quote','image'];
const tokens={ink:'#083133',accent:'#083133',muted:'#536473',line:'#dce3e8',background:'#f0f4f6'};
const uid=()=> 'c-'+Math.random().toString(36).slice(2,11);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function https(value){try{const u=new URL(value);return u.protocol==='https:'&&!!u.hostname&&!u.username&&!u.password&&!/[{}\s]/.test(value);}catch{return false;}}
function imageSource(value,email=false){return https(value)||(!email&&/^data:image\/(png|jpeg|gif|webp);base64,[a-zA-Z0-9+/=]+$/.test(value))?value:'';}
function newCard(type='announcement'){return {id:uid(),type,enabled:true,title:'',date:'',label:'',body:'',author:'',deadline:'',quote:'',buttonLabel:'',destination:'',imageUrl:'',localImage:'',imageAlt:'',approved:false};}
function linkLibrary(){return [
{id:'hub',label:'EdD Community Center',url:'https://sites.google.com/antioch.edu/eddcommunitycenter/edd-program-info',approved:true,source:'Provided in project brief'},
...['Program Calendar','Dissertation Resources','Residency','Alumni','Student Support / Information','Student Story Submission','Alumni Update Submission'].map((label,i)=>({id:['calendar','dissertation','residency','alumni','support','student-form','alumni-form'][i],label,url:'',approved:false,source:'Pending approved URL'})),
{id:'cafe',label:'Community Co-working & Café · Zoom',url:'https://antioch.zoom.us/j/94176225683',approved:true,source:'Provided by user; registration not required'}];}
function createEdition(sample=true){const now=new Date();const data={schemaVersion:1,issue:{period:'Fall',year:String(now.getFullYear()),issueDate:now.toISOString().slice(0,10),programName:'EdD Program',degreeName:'Doctor of Educational & Professional Practice',institutionName:'Antioch University',preheader:'',footerNote:''},links:linkLibrary(),sections:titles.map((title,i)=>({id:ids[i],title,enabled:true,cards:[]}))};
if(sample){data.issue.preheader='PLACEHOLDER EDITION · Demonstration content only';data.issue.footerNote='PLACEHOLDER · Replace this note with approved program contact information.';
const add=(section,type,values)=>data.sections.find(s=>s.id===section).cards.push({...newCard(type),...values});
add('update','leadership',{title:'A new chapter of learning',author:'PLACEHOLDER · Program leadership',body:'PLACEHOLDER · Add a short welcome from program leadership. Introduce the themes of this edition and invite readers into the weeks ahead.',buttonLabel:'Visit the Community Center',destination:'hub'});
add('weeks','event',{title:'PLACEHOLDER · Upcoming program gathering',body:'Replace with an approved event summary, date, and destination.',buttonLabel:'View program calendar',destination:'calendar'});
add('students','spotlight',{title:'PLACEHOLDER · Student work in focus',body:'Add an approved story celebrating a student’s scholarship or community work.',quote:'PLACEHOLDER · A short, approved quotation can bring this story to life.'});
add('cafe','event',{title:'Community Co-working & Café',body:'PLACEHOLDER · Add the upcoming session date, time, and a short invitation.',buttonLabel:'Join the Café on Zoom',destination:'cafe'});
}return P.normalize(data);}
function createPublication(type){const data=createEdition(false);delete data.publication;data.publicationType=type;data.sections=P.sections(type);return P.normalize(data);}
const exportBase=data=>P.exportBase(data);
const activeSections=data=>data.sections.filter(s=>s.enabled&&s.cards.some(c=>c.enabled));
const activeCards=data=>activeSections(data).flatMap(s=>s.cards.filter(c=>c.enabled).map(c=>({section:s,card:c})));
const editionSlug=data=>`${data.issue.period}-${data.issue.year}`.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'untitled-edition';
const placeholder=value=>/\b(placeholder|sample|lorem ipsum|tbd|todo)\b|\{\{[^}]+\}\}/i.test(value);
function validate(data,today=new Date().toLocaleDateString('en-CA')){const results=[];const add=(level,message,detail='',section='')=>results.push({level,message,detail,section});
if(data.issue.reviewNotice)add('error','Director-review mockup: not approved for distribution.','Use draft exports for review. Fictional stories and illustrative dates require replacement before publication.','issue');
for(const key of ['period','year','issueDate','programName','degreeName','institutionName'])if(!String(data.issue[key]||'').trim())add('error',`Edition ${key.replace(/([A-Z])/g,' $1').toLowerCase()} is missing.`,'Complete edition details.','issue');
if(data.issue.year&&!/^\d{4}$/.test(data.issue.year))add('error','Year must contain four digits.','','issue');
if(Object.values(data.issue).some(placeholder))add('error','Placeholder text remains in edition details.','Replace demonstration text before final export.','issue');
if(!activeCards(data).length)add('error','The edition has no enabled content.','Add at least one card to an enabled section.');
let imageCount=0,linkCount=0;
for(const s of data.sections.filter(s=>s.enabled)){
const cards=s.cards.filter(c=>c.enabled);
if(!cards.length){add('info',`${s.title} is empty and will be excluded.`,'Empty sections are omitted from both renderers.',s.id);continue;}
if(placeholder(s.title))add('error',`${s.title}: section heading contains placeholder text.`,'',s.id);
for(const c of cards){const name=c.title||'Untitled card',prefix=`${s.title} · ${name}`;
if(!c.title.trim())add('error',`${s.title}: a card needs a title.`,'',s.id);
if(![c.body,c.quote,c.imageUrl,c.localImage].some(v=>v.trim()))add('error',`${prefix}: content is missing.`,'Add a body, quotation, or image.',s.id);
if(['title','body','author','label','quote','imageAlt','buttonLabel'].some(k=>placeholder(c[k])))add('error',`${prefix}: placeholder text remains.`,'Replace demonstration copy.',s.id);

if(c.deadline&&c.deadline<today)add('warning',`${prefix}: deadline has passed.`,'Review or disable this opportunity.',s.id);
if(P.requiresApproval(s,c)&&!c.approved)add('error',`${prefix}: publication approval is not confirmed.`,'Confirm approval after reviewing the story and any image or quotation.',s.id);
if((c.buttonLabel||c.destination)&&(!c.buttonLabel.trim()||!c.destination))add('error',`${prefix}: CTA needs a label and destination.`,'Select a library destination and enter meaningful button text.',s.id);
if(c.buttonLabel&&/^(click here|here|link)$/i.test(c.buttonLabel.trim()))add('error',`${prefix}: use a descriptive button label.`,'For example, “View program calendar”.',s.id);
if(c.destination){const l=data.links.find(x=>x.id===c.destination);if(!l||!l.approved||!https(l.url))add('error',`${prefix}: destination is pending or invalid.`,'Supply an HTTPS URL in the link library and confirm it is approved.',s.id);else linkCount++;}
if(c.imageUrl||c.localImage){imageCount++;if(!c.imageAlt.trim())add('error',`${prefix}: image alt text is missing.`,'Describe the image for readers using assistive technology.',s.id);
if(c.imageUrl&&!https(c.imageUrl))add('error',`${prefix}: image URL must use HTTPS.`,'',s.id);
if(c.localImage&&!c.imageUrl)add('error',`${prefix}: local image needs a hosted HTTPS URL for email.`,'Local images are available in draft web previews only.',s.id);
}
}}
if(!results.some(r=>r.level==='error'))add('success','Content checks passed.','Ready for final export; manually verify linked destinations and image access.');
add('success',`${activeCards(data).length} enabled content card${activeCards(data).length===1?'':'s'} across ${activeSections(data).length} sections.`);
add('info',`${linkCount} approved HTTPS link reference${linkCount===1?'':'s'} configured.`,'URL format and approval checked; live availability is not checked.');
if(!results.some(r=>r.message.includes('alt text is missing')))add('success',imageCount?`All ${imageCount} images have alt text.`:'No images in this edition.');
return results;}
function linksUsed(data){return data.links.filter(l=>activeCards(data).some(({card})=>card.destination===l.id)).map(l=>({...l,usedBy:activeCards(data).filter(({card})=>card.destination===l.id).map(({section,card})=>({section:section.title,title:card.title})),availability:'Not checked'}));}
function assetsUsed(data){return activeCards(data).filter(({card})=>card.imageUrl||card.localImage).map(({section,card})=>({section:section.title,title:card.title,url:card.imageUrl||'[local preview image]',alt:card.imageAlt,emailReady:https(card.imageUrl)}));}
const paragraphs=value=>escape(value).split(/\n\s*\n/).map(v=>`<p style="margin:0 0 16px;line-height:1.7">${v.replace(/\n/g,'<br>')}</p>`).join('');
function cardMarkup(data,c,email){const dest=data.links.find(l=>l.id===c.destination),url=dest&&dest.approved&&https(dest.url)?dest.url:'',src=imageSource(c.imageUrl||c.localImage,email);
return `${src?`<img src="${escape(src)}" alt="${escape(c.imageAlt)}" width="584" style="display:block;width:100%;max-width:584px;height:auto;border:0;margin:0 0 22px">`:''}${c.label||c.date||c.deadline?`<p style="font:700 12px/1.6 Arial,sans-serif;letter-spacing:1px;color:${tokens.accent};margin:0 0 10px">${escape([c.label,c.date,c.deadline?'Deadline: '+c.deadline:''].filter(Boolean).join(' · '))}</p>`:''}<h3 style="font:normal 26px/1.25 Georgia,serif;color:${tokens.ink};margin:0 0 15px">${escape(c.title)}</h3>${c.author?`<p style="font:700 14px/1.5 Arial,sans-serif;margin:0 0 18px;color:${tokens.muted}">${escape(c.author)}</p>`:''}${c.body?paragraphs(c.body):''}${c.quote?`<blockquote style="margin:22px 0;padding:4px 0 4px 20px;border-left:3px solid ${tokens.accent};font:italic 22px/1.5 Georgia,serif;color:${tokens.accent}">${escape(c.quote)}</blockquote>`:''}${c.buttonLabel?(url?`<table role="presentation" border="0" cellspacing="0" cellpadding="0" style="margin-top:20px"><tr><td bgcolor="${tokens.accent}" style="padding:12px 20px;border-radius:3px"><a href="${escape(url)}" style="font:bold 14px/1.5 Arial,sans-serif;color:#ffffff;text-decoration:none">${escape(c.buttonLabel)} ↗</a></td></tr></table>`:`<p style="font:14px/1.6 Arial,sans-serif;color:#885607">${escape(c.buttonLabel)} · destination pending</p>`):''}`;}
function render(data,{email=false,draft=false}={}){const issue=data.issue,title=`${issue.programName} · ${issue.period} ${issue.year}`,head=`<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title>`;
const reviewNote=issue.reviewNotice?`<div style="padding:12px 20px;text-align:center;background:#e7f2ee;color:#083133;font:700 12px/1.5 Arial,sans-serif">${escape(issue.reviewNotice)}</div>`:'';
const status=data.publication?.status,showDraft=status==='Draft'||(!['Approved','Distributed'].includes(status)&&draft);
const draftNote=status==='Ready for Review'?`<div style="padding:12px 20px;text-align:center;background:#fff0d3;color:#734900;font:700 12px/1.5 Arial,sans-serif">READY FOR REVIEW · NOT APPROVED FOR DISTRIBUTION</div>`:showDraft?`<div style="padding:12px 20px;text-align:center;background:#fff0d3;color:#734900;font:700 12px/1.5 Arial,sans-serif">DRAFT PREVIEW · NOT FOR DISTRIBUTION</div>`:'';
const identity=`${data.publicationType==='program-letter'?'<p style="margin:0 0 18px;font:700 12px/1.5 Arial,sans-serif;letter-spacing:2px">EDD PROGRAM LETTER</p>':''}${issue.logoUrl&&https(issue.logoUrl)?`<img src="${escape(issue.logoUrl)}" alt="${escape(issue.logoAlt||issue.institutionName)}" width="230" style="display:block;width:230px;max-width:100%;height:auto;margin:0 0 32px;border:0">`:''}<p style="margin:0 0 26px;font:700 12px/1.5 Arial,sans-serif;letter-spacing:2px;text-transform:uppercase">${escape(issue.institutionName)}</p><h1 style="font:normal 46px/1.05 Georgia,serif;margin:0 0 14px">${escape(issue.programName)}</h1><p style="margin:0;font:16px/1.6 Arial,sans-serif">${escape(issue.degreeName)}</p><p style="margin:30px 0 0;font:700 12px/1.6 Arial,sans-serif;letter-spacing:1px;text-transform:uppercase">${escape(issue.period)} ${escape(issue.year)} &nbsp; / &nbsp; ${escape(issue.issueDate)}</p>`;
const footer=`<p style="font:700 14px/1.5 Arial,sans-serif;margin:0 0 10px">${escape(issue.programName)} · ${escape(issue.institutionName)}</p>${paragraphs(issue.footerNote)}`;
const sections=activeSections(data);
if(email)return `<!doctype html><html lang="en"><head>${head}</head><body style="margin:0;padding:0;background-color:${tokens.background};color:${tokens.ink};font-family:Arial,sans-serif"><div style="display:none;font-size:1px;line-height:1px;max-height:0;overflow:hidden;mso-hide:all">${escape(issue.preheader)}</div>${reviewNote}${draftNote}<table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="${tokens.background}"><tr><td align="center" style="padding:24px 10px"><!--[if mso]><table role="presentation" width="680"><tr><td><![endif]--><table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width:680px;background-color:#ffffff"><tr><td bgcolor="${tokens.ink}" style="padding:38px 28px;color:#ffffff">${identity}</td></tr>${sections.map(s=>`<tr><td style="padding:30px 28px 10px"><h2 style="font:bold 12px/1.6 Arial,sans-serif;text-transform:uppercase;letter-spacing:2px;border-bottom:1px solid ${tokens.line};padding-bottom:13px;margin:0;color:${tokens.accent}">${escape(s.title)}</h2></td></tr>${s.cards.filter(c=>c.enabled).map(c=>`<tr><td style="padding:20px 28px 26px;font:16px/1.7 Arial,sans-serif;color:${tokens.ink}">${cardMarkup(data,c,true)}</td></tr>`).join('')}`).join('')}<tr><td bgcolor="#eaf0f3" style="padding:30px 28px;font:14px/1.6 Arial,sans-serif;color:${tokens.muted}">${footer}</td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></body></html>`;
return `<!doctype html><html lang="en"><head>${head}<style>body{margin:0;background:${tokens.background};color:${tokens.ink};font:16px/1.7 Arial,sans-serif}*{box-sizing:border-box}.newsletter{max-width:760px;margin:auto;background:white}.masthead{padding:44px 44px 40px;background:${tokens.ink};color:white;border-bottom:6px solid ${tokens.accent}}main{padding:12px 44px 35px}section>h2{font:700 12px/1.6 Arial,sans-serif;text-transform:uppercase;letter-spacing:2px;color:${tokens.accent};margin:28px 0 0;border-bottom:1px solid ${tokens.line};padding-bottom:14px}article{padding:28px 0;border-bottom:1px solid ${tokens.line}}article:last-child{border:0}footer{padding:30px 44px;background:#eaf0f3;font-size:14px;color:${tokens.muted}}p,h1,h2,h3,a{overflow-wrap:anywhere}@media(max-width:480px){.masthead{padding:32px 24px}.masthead h1{font-size:38px!important}main{padding:8px 24px 24px}footer{padding:26px 24px}article{padding:24px 0}}</style></head><body>${reviewNote}${draftNote}<div class="newsletter"><header class="masthead">${identity}</header><main>${issue.preheader?`<p style="color:${tokens.muted};font-size:14px;padding-top:18px">${escape(issue.preheader)}</p>`:''}${sections.map(s=>`<section><h2>${escape(s.title)}</h2>${s.cards.filter(c=>c.enabled).map(c=>`<article>${cardMarkup(data,c,false)}</article>`).join('')}</section>`).join('')||'<p style="padding:30px 0">Your newsletter begins here. Add content cards in the editor.</p>'}</main><footer>${footer}</footer></div></body></html>`;}
function makeFiles(data,{draft=false}={}){if(!draft&&validate(data).some(r=>r.level==='error'))throw new Error('Resolve readiness blockers before final export.');const slug=editionSlug(data),prefix=`${exportBase(data)}${draft?'-draft':''}`;return {[prefix+'.html']:render(data,{draft}),[prefix+'-email.html']:render(data,{email:true,draft}),'content.json':JSON.stringify(data,null,2),'links-used.json':JSON.stringify(linksUsed(data),null,2),'README.txt':`${draft?'DRAFT — NOT FOR DISTRIBUTION\n\n':''}EdD Communications Studio\nPublication: ${P.label(data)}\nEdition: ${slug}\n\nFiles\n- ${prefix}.html: standalone browser newsletter\n- ${prefix}-email.html: table-based email HTML with inline CSS\n- content.json: complete editable edition and link library; import into the Studio\n- links-used.json: centralized destinations referenced by enabled cards\n\n${draft?'Draft email omits local preview images; pending destinations have no active link.\n':''}Image assets\n${JSON.stringify(assetsUsed(data),null,2)}\n\nReadiness results at export\n${validate(data).map(r=>r.level.toUpperCase()+': '+r.message).join('\n')}\n\nLimitations\nLinks and images require manual access checks. HTTPS syntax and approval do not verify availability. Test email rendering in the institution-approved sending platform, Gmail, and Outlook before distribution. No sending or subscriber management is included. Visual colors are prototype tokens, not confirmed Antioch branding. Remote images remain remote and require internet access.\n`};}
// Stored ZIP archive: no dependency, no network, and interoperable with standard unzip tools.
function zip(files){const encoder=new TextEncoder(),parts=[],central=[];let offset=0;const crc=b=>{let c=0xffffffff;for(const n of b){c^=n;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;};
for(const [name,value] of Object.entries(files)){const n=encoder.encode(name),b=encoder.encode(value),sum=crc(b),h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,33,true);v.setUint32(14,sum,true);v.setUint32(18,b.length,true);v.setUint32(22,b.length,true);v.setUint16(26,n.length,true);h.set(n,30);parts.push(h,b);const d=new Uint8Array(46+n.length),w=new DataView(d.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint16(14,33,true);w.setUint32(16,sum,true);w.setUint32(20,b.length,true);w.setUint32(24,b.length,true);w.setUint16(28,n.length,true);w.setUint32(42,offset,true);d.set(n,46);central.push(d);offset+=h.length+b.length;}
const end=new Uint8Array(22),v=new DataView(end.buffer),size=central.reduce((sum,p)=>sum+p.length,0);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);const all=[...parts,...central,end],out=new Uint8Array(all.reduce((sum,p)=>sum+p.length,0));let pos=0;for(const p of all){out.set(p,pos);pos+=p.length;}return out;}
function parseEdition(text){const d=JSON.parse(text);if(d?.schemaVersion!==1||!d.issue||!Array.isArray(d.sections)||!Array.isArray(d.links))throw new Error('Not a supported Studio edition (schemaVersion 1).');const base=createEdition(false);for(const k of Object.keys(base.issue))if(typeof d.issue[k]!=='string')throw new Error(`Invalid edition field: ${k}`);for(const key of ['logoUrl','logoAlt','reviewNotice'])if(d.issue[key]!==undefined&&typeof d.issue[key]!=='string')throw new Error('Invalid optional edition field: '+key);if(d.sections.length>100||d.links.length>500)throw new Error('Edition exceeds prototype limits.');const seen=new Set();for(const s of d.sections){if(!s||typeof s.id!=='string'||!s.id||seen.has(s.id)||typeof s.title!=='string'||typeof s.enabled!=='boolean'||!Array.isArray(s.cards))throw new Error('Invalid or duplicate section.');seen.add(s.id);if(s.cards.length>500)throw new Error('Too many cards.');for(const c of s.cards){for(const [k,v] of Object.entries(newCard()))if(typeof c[k]!==typeof v)throw new Error(`Invalid card field: ${k}`);if(c.externalSubmission!==undefined&&typeof c.externalSubmission!=='boolean')throw new Error('Invalid submission review flag.');if(!types.includes(c.type)||seen.has(c.id))throw new Error('Invalid card type or duplicate ID.');seen.add(c.id);if(c.localImage&&!imageSource(c.localImage))throw new Error('Unsupported local image.');}}const linkIds=new Set();for(const l of d.links){if(!l||typeof l.id!=='string'||!l.id||linkIds.has(l.id)||typeof l.label!=='string'||typeof l.url!=='string'||typeof l.approved!=='boolean')throw new Error('Invalid link entry.');linkIds.add(l.id);}return P.normalize(d);}
const api={titles,ids,types,tokens,escape,https,imageSource,newCard,createEdition,createPublication,exportBase,activeSections,activeCards,editionSlug,validate,linksUsed,assetsUsed,render,makeFiles,zip,parseEdition};
if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Studio=api;
})(typeof window!=='undefined'?window:this);
