(function(root){
'use strict';
const S=typeof module!=='undefined'&&module.exports?require('./core.js'):root.Studio;
function createDirectorSample(){
const d=S.createEdition(false);
d.issue={...d.issue,period:'Fall · Inquiry into action',year:'2026',issueDate:'2026-10-01',preheader:'Learning with communities. Asking better questions. Turning scholarship into meaningful change.',footerNote:'Director-review mockup • October 2026\nEditorial messages, events, spotlight narratives, and quotations in this demonstration are fictional. Dates are illustrative, not an official schedule. Resource links point to existing university destinations. Photography is illustrative Antioch brand imagery; the people pictured are not the subjects of the fictional stories.\nFor current program information, visit the EdD Community Center. Thank you for helping build a thoughtful, connected community of practice.',reviewNotice:'DIRECTOR-REVIEW MOCKUP · Illustrative stories and dates · Not for distribution',logoUrl:'https://brand.antioch.edu/wp-content/uploads/sites/7/2025/11/AU-Logo_stacked_white.png',logoAlt:'Antioch University'};
const sources={program:'https://www.antioch.edu/academics/education/edd-in-educational-professional-practice/',dissertation:'https://libguides.antioch.edu/dhq',writing:'https://www.antioch.edu/departments/writing-centers/',access:'https://www.antioch.edu/resources/students/disability-services/',news:'https://commonthread.antioch.edu/'};
for(const [id,url] of Object.entries(sources)){const old=d.links.find(l=>l.id===id);const values={id,label:{program:'EdD program overview',dissertation:'Antioch Library · Dissertation HQ',writing:'Antioch writing support',access:'Disability Support Services',news:'Common Thread · University news'}[id],url,approved:true,source:'Official Antioch website; selected for director-review demonstration. Publication approval still required.'};if(old)Object.assign(old,values);else d.links.push(values);}
const add=(sid,type,values)=>d.sections.find(s=>s.id===sid).cards.push({...S.newCard(type),...values});
add('update','leadership',{title:'Inquiry into action',label:'A letter to our learning community',author:'Program leadership · demonstration message',body:'The questions that matter most rarely stay inside a classroom. They emerge in staff meetings, community conversations, learning spaces, and the moments when familiar approaches stop working. This season, we invite our EdD community to bring those questions into conversation with one another.\n\nOur theme is simple: listen closely, investigate thoughtfully, and share what you learn. A useful next step might be a more inclusive meeting, a sharper research question, or a new partnership shaped with—not merely for—the people it serves.\n\nIn this edition, we explore the connections between reflective practice, belonging, and public scholarship. Wherever you are in your doctoral journey, make room for a colleague’s perspective and for the possibility that your next insight will begin with a better question.',quote:'What changes when we treat the people closest to a challenge as partners in understanding it?',buttonLabel:'Explore the EdD program',destination:'program',imageUrl:'https://brand.antioch.edu/wp-content/uploads/sites/7/2021/02/grad-leadership-ads2-1024x691.png',imageAlt:'Two adults in conversation on a sofa; illustrative imagery from the Antioch University brand guide.'});
add('weeks','event',{title:'Writing together: a focused hour',date:'2026-10-08',label:'Illustrative date · 6–7 p.m. Eastern · Online',body:'Bring one achievable goal: revise a paragraph, map an argument, or organize a set of research notes. Begin with a brief check-in, work quietly alongside peers, and close by naming your next step. Demonstration event; consult the Community Center for actual dates.',buttonLabel:'Visit the Community Center',destination:'hub'});
add('weeks','event',{title:'Problems of practice, shared perspectives',date:'2026-10-15',label:'Illustrative date · 7–8 p.m. Eastern · Online',body:'A discussion-format workshop invites participants to describe a challenge from their professional setting and examine whose perspectives are represented. Leave with one question worth investigating. Demonstration event, not an announced program session.'});
add('weeks','event',{title:'Dissertation conversation: from question to design',date:'2026-10-22',label:'Illustrative date · 6–7 p.m. Eastern · Online',body:'Explore the relationship between a research question, the evidence needed to address it, and the practical realities of gathering that evidence. Demonstration session; no defense or candidate is being announced.',buttonLabel:'Explore Dissertation HQ',destination:'dissertation'});
add('community','announcement',{title:'Connection is part of the work',label:'Community practice',body:'Doctoral work can be solitary; it does not have to be isolating. Try a small peer check-in: share one idea that is taking shape, one obstacle, and one specific kind of feedback you would welcome. Listening before advising makes room for different contexts and different ways of knowing.\n\nFor your next conversation, bring an artifact of practice—a meeting agenda, a learning activity, or a question from a community partner—and ask what it reveals about participation and voice.',quote:'A strong learning community makes it easier to ask an unfinished question.',buttonLabel:'Return to our community space',destination:'hub'});
add('community','announcement',{title:'The five-minute reading exchange',label:'Try this with a peer',body:'Choose one passage from a reading that challenged an assumption. In a brief exchange, explain why it stayed with you and ask your partner what it brings to mind in their own setting. Resist the urge to agree too quickly: a useful conversation can reveal where the same idea meets different realities.',quote:'What does this idea help us see—and what might it leave out?'});
add('dissertation','resource',{title:'From a compelling concern to a researchable question',label:'The dissertation journey',body:'A problem of practice begins with a concern you can describe clearly in context. Before narrowing a question, write a short account of who experiences the problem, what you currently know, and what remains uncertain.\n\nThen consider the fit: what evidence would help answer the question, who should shape the inquiry, and what is feasible within your setting? Bring that working account to your next advising conversation. The goal is not a perfect first formulation; it is a defensible next step.',buttonLabel:'Visit Dissertation HQ',destination:'dissertation'});
add('dissertation','announcement',{title:'A milestone worth recognizing',label:'Illustrative milestone feature',body:'This space can celebrate a proposal moving forward, an approved research plan, a completed analysis, or a successful defense. For this mockup, the featured milestone is a fictional practitioner’s move from a broad interest in belonging to a focused study of how adults experience participation in team learning.\n\nThe story behind the milestone matters: careful revision, thoughtful feedback, and persistence. No actual dissertation approval or defense result is being reported.'});
add('residency','announcement',{title:'Arrive with a question. Leave with a connection.',label:'Preparing for residency',body:'Residency creates an opportunity to connect sustained inquiry with shared conversation. Prepare a two-minute introduction to your current work, choose an artifact that illustrates your practice, and identify a question that would benefit from perspectives beyond your own field.\n\nBuild in time to listen, reflect, and follow up. Afterward, send one colleague a resource or question that continues the conversation. Confirm all schedules, locations, and preparation requirements through official program communications.',buttonLabel:'View official program information',destination:'program'});
add('students','spotlight',{title:'Making room for every voice',label:'Student spotlight · fictional composite',author:'An educator’s inquiry into belonging',body:'In this fictional composite story, a school-based educator notices that the same few voices tend to shape professional learning meetings. Rather than assuming that silence means agreement, the practitioner begins asking how the meeting itself might influence participation.\n\nTheir developing inquiry considers reflective writing, smaller discussion groups, and opportunities to contribute before and after a meeting. The emphasis is on listening to colleagues and examining the conditions that help people participate.\n\nThe story illustrates the kind of practice-centered student feature this newsletter could carry. It does not describe a real Antioch student, study, or research finding.',quote:'I began by asking how to improve participation. I am learning to ask who gets to define what participation looks like.'});
add('alumni','spotlight',{title:'Carrying inquiry beyond the dissertation',label:'Alumni connection · fictional composite',author:'A continuing practice of learning with others',body:'In this fictional alumni profile, a community-organization leader carries a reflective inquiry habit into everyday work. The team sets aside time to examine a service experience from the perspective of the people who use it, then invites those participants to help shape the next questions.\n\nThe most valuable change is not a new title or a finished report. It is a more deliberate routine: notice assumptions, seek perspectives that are missing, and make decisions that can be revisited as understanding grows.\n\nThis narrative demonstrates an alumni feature format. It is not an account of an actual graduate or an attributed professional accomplishment.',quote:'The degree may end, but the responsibility to keep asking better questions continues.',buttonLabel:'Read university community stories',destination:'news'});
add('scholarship','announcement',{title:'Scholarship that travels beyond the seminar',label:'Research & public scholarship',body:'Who could use your ideas beyond an academic audience? Consider a short practice brief, a facilitated conversation, or a visual explanation that helps a community partner engage with a question. Begin with what the audience needs to understand, and make the limits of the evidence as clear as the possibilities.\n\nEnvironmental learning offers one useful lens: questions about place, responsibility, and participation can bring professional practice into conversation with community priorities. The photograph is illustrative brand imagery, not documentation of an EdD research project.',imageUrl:'https://brand.antioch.edu/wp-content/uploads/sites/7/2021/02/GettyImages-515306702.jpg',imageAlt:'An adult standing among plants in a greenhouse, with Antioch brand graphics; illustrative image, not a featured student.',buttonLabel:'Explore Common Thread',destination:'news'});
add('opportunities','opportunity',{title:'Turn one idea into a practice brief',label:'An invitation to share your thinking',body:'Choose a question from your professional setting and draft a one-page brief for a nonacademic audience. Describe the context, explain why the question matters, and offer one carefully qualified implication for practice. Ask a colleague outside your specialization to read it for clarity.\n\nThis is an editorial activity for the mockup, not a funded opportunity, formal call for proposals, or required assignment.'});
add('opportunities','opportunity',{title:'Find the conversation your work belongs in',label:'Professional learning',body:'As you consider workshops, conferences, and community forums, look for audiences connected to your problem of practice. Review the purpose, accessibility, cost, and submission requirements before committing. A small local conversation can be as useful as a large conference when the right partners are at the table.',buttonLabel:'Explore university news and events coverage',destination:'news'});
add('resources','resource',{title:'Make space for the next draft',label:'Writing & research support',body:'When writing feels stalled, separate the tasks. Use one session to clarify the claim, another to organize evidence, and a third to revise for a reader. Bring a focused question when seeking feedback: “Where does the argument become difficult to follow?” is often more useful than “Is this good?”',buttonLabel:'Find Antioch writing support',destination:'writing'});
add('resources','resource',{title:'Access belongs in the plan',label:'Resources & wellbeing',body:'Plan your learning with access and sustainability in mind. Protect a realistic work rhythm, identify the support you need, and use official university channels to discuss accommodations. You do not have to solve every barrier on your own.',buttonLabel:'Visit Disability Support Services',destination:'access'});
add('cafe','event',{title:'A little company. A little progress.',date:'2026-10-29',label:'Illustrative session · 6–7 p.m. Eastern · Online',body:'Bring your writing, reading, or planning—and a cup of whatever helps you settle in. Our demonstration Café format opens with a friendly check-in, makes space for focused work, and closes with a brief reflection. You can arrive with a small goal and leave with a little momentum.\n\nThis date and time are illustrative. Confirm the actual session schedule through the Community Center before joining. The button uses the program’s supplied Café Zoom destination; no registration is required.',buttonLabel:'Open the Café Zoom room',destination:'cafe'});
add('connect','resource',{title:'Keep the conversation going',label:'Stay connected / Need help',body:'Let the newsletter be your starting point and the Community Center your home for current program information. Return there for updates, resources, and the appropriate program contact pathways.\n\nHave a story about your learning, practice, or community work? Prepare a short summary and confirm the program’s current submission process. Stories and photographs should be reviewed and approved before publication; this mockup does not collect submissions.',buttonLabel:'Visit the EdD Community Center',destination:'hub'});
return d;
}
if(typeof module!=='undefined'&&module.exports)module.exports=createDirectorSample;else root.createDirectorSample=createDirectorSample;
})(typeof window!=='undefined'?window:this);
