const {test}=require('node:test'),assert=require('node:assert/strict'),S=require('../core.js');
function ready(){const d=S.createEdition(false);d.sections[0].cards.push({...S.newCard('leadership'),title:'Welcome',body:'A message for our learning community.'});return d;}
test('placeholder sample is blocked; no invented readiness counts',()=>{const d=S.createEdition();const r=S.validate(d);assert(r.some(x=>x.message.includes('placeholder')));assert.throws(()=>S.makeFiles(d),/blockers/);assert(!r.some(x=>x.message.includes('11 valid links')||x.message.includes('Defense #2')));});
test('complete edition exports both renderers and exact five bundle files',()=>{const d=ready();assert(!S.validate(d).some(r=>r.level==='error'));const f=S.makeFiles(d);assert.equal(Object.keys(f).length,5);const email=f[`edd-newsletter-${S.editionSlug(d)}-email.html`];assert.match(email,/<table role="presentation"/);assert.doesNotMatch(email,/<(script|form|iframe)\b/i);assert.doesNotMatch(email,/DRAFT PREVIEW/);});
test('disabled cards and empty sections do not render or block',()=>{const d=ready();d.sections[1].cards.push({...S.newCard('event'),enabled:false,title:'PLACEHOLDER'});assert(!S.validate(d).some(r=>r.level==='error'));assert.doesNotMatch(S.render(d),/The Weeks Ahead|Residency|PLACEHOLDER/);});
test('section and card order is preserved',()=>{const d=ready();d.sections[2].cards.push({...S.newCard(),title:'Second heading',body:'Second body'});d.sections.reverse();const html=S.render(d);assert(html.indexOf('Second heading')<html.indexOf('Welcome'));});
test('student approval required and excluded sections ignored',()=>{const d=ready(),s=d.sections.find(s=>s.id==='students');s.cards.push({...S.newCard('spotlight'),title:'Scholarship',body:'An editorial story.'});assert(S.validate(d).some(r=>r.message.includes('approval')));s.cards[0].approved=true;assert(!S.validate(d).some(r=>r.level==='error'));s.cards[0].approved=false;s.enabled=false;assert(!S.validate(d).some(r=>r.level==='error'));});
test('pending, unsafe and unapproved links block final export',()=>{const d=ready(),c=d.sections[0].cards[0];c.buttonLabel='View calendar';c.destination='calendar';assert(S.validate(d).some(r=>r.message.includes('destination is pending')));const l=d.links.find(l=>l.id==='calendar');l.url='javascript:alert(1)';l.approved=true;assert.doesNotMatch(S.render(d),/href="javascript:/);l.url='https://example.org/calendar';assert(!S.validate(d).some(r=>r.level==='error'));assert.equal(S.linksUsed(d).length,1);assert.equal(S.linksUsed(d)[0].usedBy[0].title,'Welcome');});
test('Cafe does not require registration',()=>{const d=ready(),s=d.sections.find(s=>s.id==='cafe');s.cards.push({...S.newCard('event'),title:'Co-working',body:'Join the session.',date:'2030-01-20',destination:'cafe',buttonLabel:'Join on Zoom'});assert(!S.validate(d).some(r=>r.level==='error'));assert.match(S.render(d,{email:true}),/https:\/\/antioch.zoom.us\/j\/94176225683/);});
test('local images and missing alt block email; draft web embeds image',()=>{const d=ready(),c=d.sections[0].cards[0];c.localImage='data:image/png;base64,aGVsbG8=';assert(S.validate(d).some(r=>r.message.includes('alt text')));assert(S.validate(d).some(r=>r.message.includes('hosted HTTPS')));assert.match(S.render(d,{draft:true}),/data:image\/png/);assert.doesNotMatch(S.render(d,{draft:true,email:true}),/data:image\/png/);c.imageUrl='https://example.org/image.png';c.imageAlt='Students working together';assert(!S.validate(d).some(r=>r.level==='error'));});
test('event date and expired opportunity derive from current data',()=>{const d=ready(),c=d.sections[0].cards[0];c.type='event';assert(S.validate(d).some(r=>r.message.includes('event date')));c.date='2030-01-20';c.deadline='2000-01-01';assert(S.validate(d,'2026-09-25').some(r=>r.level==='warning'&&r.message.includes('deadline')));});
test('HTML content and attributes are escaped',()=>{const d=ready(),c=d.sections[0].cards[0];c.title='<script>alert(1)</script>';c.body='<img src=x onerror=alert(1)>';const html=S.render(d);assert.doesNotMatch(html,/<script>|<img src=x/);assert.match(html,/&lt;script&gt;/);});
test('JSON import validates structure and preserves a round trip',()=>{const d=ready();assert.deepEqual(S.parseEdition(JSON.stringify(d)),d);assert.throws(()=>S.parseEdition('{}'));d.sections[0].cards[0].enabled='true';assert.throws(()=>S.parseEdition(JSON.stringify(d)));});
test('ZIP contains correct local header, central directory, UTF-8 names and CRC',()=>{const bytes=S.zip({'output/test/café.txt':'Hello edition'}),v=new DataView(bytes.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint32(bytes.length-22,true),0x06054b50);assert.equal(v.getUint16(bytes.length-14,true),1);assert.equal(v.getUint16(6,true),0x800);assert(new TextDecoder().decode(bytes).includes('café.txt'));});
