const {test}=require('node:test'),assert=require('node:assert/strict');
const S=require('../core.js'),H=require('../handoff.js');
function fixture(){const d=S.createEdition(false);d.issue.preheader='Hidden preview snippet';d.sections[0].cards.push({...S.newCard(),title:'Community & learning',body:'Welcome to this edition.',destination:'hub',buttonLabel:'Visit Community Center'});return d;}
test('Gmail fragment retains rendered content and inline styling, excludes document and hidden preheader',()=>{const source=S.render(fixture(),{email:true});const html=H.emailFragment(source);assert.doesNotMatch(html,/<(?:html|head|title|body|script|iframe|button)\b/i);assert.doesNotMatch(html,/Hidden preview snippet|display:none/);assert.match(html,/<table role="presentation"/);assert.match(html,/Community &amp; learning/);assert.match(html,/style="margin:0;padding:0;background-color:/);assert.match(source,/Hidden preview snippet/);});
test('plain-text fallback decodes copy, preserves links, and contains no source markup',()=>{const text=H.plainText(H.emailFragment(S.render(fixture(),{email:true})));assert.match(text,/Community & learning/);assert.match(text,/https:\/\/sites.google.com/);assert.doesNotMatch(text,/<table|<div|Hidden preview snippet|\[if mso\]/);});
test('clipboard writes HTML and plain text together',async()=>{let entries;class Item{constructor(data){this.data=data;}}const html=H.emailFragment(S.render(fixture(),{email:true}));const result=await H.copyRendered(html,{clipboard:{write:async items=>entries=items},ClipboardItem:Item,Blob});assert.equal(result.mode,'rich');assert.equal(await entries[0].data['text/html'].text(),html);assert.equal(await entries[0].data['text/plain'].text(),H.plainText(html));});
test('unsupported or denied HTML clipboard falls back to text, never source',async()=>{let copied;class Item{constructor(data){this.data=data;}}const result=await H.copyRendered('<p>Hello &amp; welcome</p>',{clipboard:{write:async()=>{throw Error('unsupported');},writeText:async text=>copied=text},ClipboardItem:Item,Blob});assert.equal(result.mode,'text');assert.equal(copied,'Hello & welcome');});
test('unavailable clipboard yields manual text fallback',async()=>{const result=await H.copyRendered('<p>Hello</p>',{});assert.deepEqual(result,{mode:'manual',text:'Hello'});});
test('draft marker survives Gmail copy while preheader stays excluded',()=>{const html=H.emailFragment(S.render(fixture(),{email:true,draft:true}));assert.match(html,/DRAFT PREVIEW/);assert.doesNotMatch(html,/Hidden preview snippet/);});
